site_name: passbook Docs
site_url: https://beryju.github.io/passbook
copyright: "Copyright &copy; 2019 - 2020 BeryJu.org"

nav:
  - Home: index.md
  - Installation:
      - Installation: installation/install.md
      - docker-compose: installation/docker-compose.md
      - Kubernetes: installation/kubernetes.md
  - Sources: sources.md
  - Providers: providers.md
  - Property Mappings:
      - Overview: property-mappings/index.md
      - Reference:
          - User Object: property-mappings/reference/user-object.md
  - Factors: factors.md
  - Policies:
      - Overview: policies/index.md
      - Expression: policies/expression/index.md
  - Integrations:
      - as Provider:
          - Amazon Web Services: integrations/services/aws/index.md
          - GitLab: integrations/services/gitlab/index.md
          - Rancher: integrations/services/rancher/index.md
          - Harbor: integrations/services/harbor/index.md
          - Sentry: integrations/services/sentry/index.md
          - Ansible Tower/AWX: integrations/services/tower-awx/index.md

repo_name: "BeryJu.org/passbook"
repo_url: https://github.com/BeryJu/passbook
theme:
  name: "material"
  logo: "images/logo.svg"

markdown_extensions:
  - toc:
      permalink: "Â¶"
  - admonition
