site_name: passbook Docs
site_url: https://passbook.beryju.org/
copyright: "Copyright &copy; 2019 - 2020 BeryJu.org"

nav:
  - Home: index.md
  - Terminology: terminology.md
  - Installation:
    - docker-compose: installation/docker-compose.md
    - Kubernetes: installation/kubernetes.md
    - Reverse Proxy: installation/reverse-proxy.md
  - Flows:
      Overview: flow/flows.md
      Examples: flow/examples/examples.md
  - Stages:
    - Captcha Stage: flow/stages/captcha/index.md
    - Dummy Stage: flow/stages/dummy/index.md
    - Email Stage: flow/stages/email/index.md
    - Identification Stage: flow/stages/identification/index.md
    - Invitation Stage: flow/stages/invitation/index.md
    - OTP Stage: flow/stages/otp/index.md
    - Password Stage: flow/stages/password/index.md
    - Prompt Stage: flow/stages/prompt/index.md
    - Prompt Stage Validation: flow/stages/prompt/validation.md
    - User Delete Stage: flow/stages/user_delete.md
    - User Login Stage: flow/stages/user_login.md
    - User Logout Stage: flow/stages/user_logout.md
    - User Write Stage: flow/stages/user_write.md
  - Sources: sources.md
  - Providers:
    - OAuth2: providers/oauth2.md
    - SAML: providers/saml.md
    - Proxy: providers/proxy.md
  - Outposts:
    - Overview: outposts/outposts.md
    - Upgrading: outposts/upgrading.md
    - Deploy on docker-compose: outposts/deploy-docker-compose.md
    - Deploy on Kubernetes: outposts/deploy-kubernetes.md
  - Expressions:
    - Overview: expressions/index.md
    - Reference:
      - User Object: expressions/reference/user-object.md
  - Property Mappings:
    - Overview: property-mappings/index.md
    - Expressions: property-mappings/expression.md
  - Policies:
    - Overview: policies/index.md
    - Expression: policies/expression.md
  - Integrations:
    - as Provider:
        - Amazon Web Services: integrations/services/aws/index.md
        - GitLab: integrations/services/gitlab/index.md
        - Rancher: integrations/services/rancher/index.md
        - Harbor: integrations/services/harbor/index.md
        - Sentry: integrations/services/sentry/index.md
        - Ansible Tower/AWX: integrations/services/tower-awx/index.md
        - VMware vCenter: integrations/services/vmware-vcenter/index.md
        - Ubuntu Landscape: integrations/services/ubuntu-landscape/index.md
        - Sonarr: integrations/services/sonarr/index.md
        - Tautulli: integrations/services/tautulli/index.md
  - Maintenance:
    - Backups: maintenance/backups/index.md
  - Upgrading:
    - to 0.9: upgrading/to-0.9.md
    - to 0.10: upgrading/to-0.10.md
  - Troubleshooting:
    - Access problems: troubleshooting/access.md

repo_name: "BeryJu/passbook"
repo_url: https://github.com/BeryJu/passbook
theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    scheme: slate
    primary: white

markdown_extensions:
  - toc:
      permalink: "Â¶"
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - attr_list

plugins:
  - search
