[package]
name = "authentik"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true
default-run = "authentik"

[dependencies]
miette.workspace = true
clap.workspace = true
shadow-rs.workspace = true

authentik-server.workspace = true

[build-dependencies]
shadow-rs.workspace = true

[lints]
workspace = true
