apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "authentik.fullname" . }}-secret-key
data:
  monitoring_username: bW9uaXRvcg== # monitor in base64
  {{- if .Values.config.secretKey }}
  secret_key: {{ .Values.config.secretKey | b64enc | quote }}
  {{- else }}
  secret_key: {{ randAlphaNum 50 | b64enc | quote}}
  {{- end }}
  {{- if .Values.backup }}
  POSTGRESQL__S3_BACKUP__SECRET_KEY: "{{ .Values.backup.secretKey }}"
  {{- end}}
  EMAIL__PASSWORD: "{{ .Values.config.email.password }}"
