dependencies:
- name: postgresql
  version: 5.3.9
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 9.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
