---
services:
  diff:
    image: docker.io/openapitools/openapi-diff:2.1.6
    restart: never
    network_mode: none
    volumes:
      - ${LOCAL_PROJECT_DIR:-../../}:/local

  gen:
    image: docker.io/openapitools/openapi-generator-cli:v7.16.0
    restart: never
    network_mode: none
    volumes:
      - ${LOCAL_PROJECT_DIR:-../../}:/local
