templateDir: /local/scripts/api/ts-templates/
additionalProperties:
  typescriptThreePlus: true
  supportsES6: true
  npmName: "@goauthentik/api"
  fileContentDataType: Blob
  enumUnknownDefaultCase: true
  useObjectParameters: true
files:
  README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
