version: "3.7"

services:
  postgresql:
    container_name: postgres
    image: docker.io/library/postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: authentik
    ports:
      - 127.0.0.1:5432:5432
    restart: always
  redis:
    container_name: redis
    image: docker.io/library/redis
    ports:
      - 127.0.0.1:6379:6379
    restart: always
  spotlight:
    image: ghcr.io/getsentry/spotlight
    ports:
      - 127.0.0.1:8969:8969
    restart: always

volumes:
  db-data:
    driver: local
