[project]
name = "django-postgres-cache"
version = "0.1.0"
description = "Improved Django Postgres Cache"
requires-python = ">=3.9,<3.15"
readme = "README.md"
license = "MIT"
authors = [{ name = "Authentik Security Inc.", email = "hello@goauthentik.io" }]
keywords = ["django", "cache", "postgres"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 4.2",
  "Framework :: Django :: 5.0",
  "Framework :: Django :: 5.1",
  "Framework :: Django :: 5.2",
  "Intended Audience :: Developers",
  "Operating System :: MacOS",
  "Operating System :: POSIX",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
  "django >=4.2,<6.0",
  "django-postgres-extra >=2.0,<2.1",
]

[project.urls]
Homepage = "https://github.com/goauthentik/authentik/tree/main/packages/django-postgres-cache"
Documentation = "https://github.com/goauthentik/authentik/tree/main/packages/django-postgres-cache"
Repository = "https://github.com/goauthentik/authentik/tree/main/packages/django-postgres-cache"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.packages]
find = {}
