apiVersion: v2
appVersion: "0.10.0-rc6"
description: A Helm chart for passbook.
name: passbook
version: "0.10.0-rc6"
icon: https://github.com/BeryJu/passbook/blob/master/docs/images/logo.svg
dependencies:
  - name: postgresql
    version: 9.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: install.postgresql
  - name: redis
    version: 10.7.16
    repository: https://charts.bitnami.com/bitnami
    condition: install.redis
