apiVersion: v2
description: authentik is an open-source Identity Provider focused on flexibility and versatility. You can use authentik in an existing environment to add support for new protocols. authentik is also a great solution for implementing signup/recovery/etc in your application, so you don't have to deal with it.
name: authentik
home: https://goauthentik.io
sources:
  - https://github.com/BeryJu/authentik
version: "2021.1.1-rc1"
icon: https://raw.githubusercontent.com/BeryJu/authentik/master/web/icons/icon.svg
dependencies:
  - name: postgresql
    version: 9.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: install.postgresql
  - name: redis
    version: 10.9.0
    repository: https://charts.bitnami.com/bitnami
    condition: install.redis
