version: "3.5"

services:
  passbook_gatekeeper:
    image: beryju/passbook-gatekeeper:{{ version }}
    ports:
      - 4180:4180
    environment:
      OAUTH2_PROXY_CLIENT_ID: {{ provider.client.client_id }}
      OAUTH2_PROXY_CLIENT_SECRET: {{ provider.client.client_secret }}
      OAUTH2_PROXY_REDIRECT_URL: https://{{ provider.external_host }}/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://{{ request.META.HTTP_HOST }}/application/oidc
      OAUTH2_PROXY_COOKIE_SECRET: {{ cookie_secret }}
      OAUTH2_PROXY_UPSTREAMS: http://{{ provider.internal_host }}
