---
name: CI - Main daily

on:
  workflow_dispatch:
  schedule:
    # Every night at 3am
    - cron: "0 3 * * *"

jobs:
  test-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - docs
          - version-2025-4
          - version-2025-2
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v5
      - run: |
          current="$(pwd)"
          dir="/tmp/authentik/${{ matrix.version }}"
          mkdir -p $dir
          cd $dir
          wget https://${{ matrix.version }}.goauthentik.io/docker-compose.yml
          ${current}/scripts/test_docker.sh
