name: authentik-ci-website

on:
  push:
    branches:
      - main
      - next
      - version-*
  pull_request:
    branches:
      - main

jobs:
  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: website/package-lock.json
      - working-directory: website/
        run: npm ci
      - name: prettier
        working-directory: website/
        run: npm run prettier-check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: website/package-lock.json
      - working-directory: website/
        run: npm ci
      - name: test
        working-directory: website/
        run: npm test
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.job }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - build
          - build-docs-only
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: website/package-lock.json
      - working-directory: website/
        run: npm ci
      - name: build
        working-directory: website/
        run: npm run ${{ matrix.job }}
  ci-website-mark:
    needs:
      - lint-prettier
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - run: echo mark
