name: authentik-gen-update-fido-mds3
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 1,15 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup authentik env
        uses: ./.github/actions/setup
      - run: poetry run ak update_fido_mds3
      - uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: update-fido-mds-client
          commit-message: "stages/authenticator_webauthn: Update FIDO MDS3 blob"
          title: "stages/authenticator_webauthn: Update FIDO MDS3 blob"
          body: "stages/authenticator_webauthn: Update FIDO MDS3 blob"
          delete-branch: true
          signoff: true
          # ID from https://api.github.com/users/authentik-automation[bot]
          author: authentik-automation[bot] <135050075+authentik-automation[bot]@users.noreply.github.com>
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
