---
name: Packages - Publish NPM packages

on:
  push:
    branches: [main]
    paths:
      - packages/docusaurus-config/**
      - packages/eslint-config/**
      - packages/prettier-config/**
      - packages/tsconfig/**
      - packages/esbuild-plugin-live-reload/**
  workflow_dispatch:

permissions:
  # Required for NPM OIDC trusted publisher
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - packages/docusaurus-config
          - packages/eslint-config
          - packages/prettier-config
          - packages/tsconfig
          - packages/esbuild-plugin-live-reload
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 2
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v5
        with:
          node-version-file: ${{ matrix.package }}/package.json
          registry-url: "https://registry.npmjs.org"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # 24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          files: |
            ${{ matrix.package }}/package.json
      - name: Publish package
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ${{ matrix.package }}
        run: |
          npm ci
          npm run build
          npm publish
