---
name: Repo - Cleanup internal mirror

on:
  workflow_dispatch:

jobs:
  to_internal:
    if: ${{ github.repository != 'goauthentik/authentik-internal' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - if: ${{ env.MIRROR_KEY != '' }}
        uses: BeryJu/repository-mirroring-action@5cf300935bc2e068f73ea69bcc411a8a997208eb
        with:
          target_repo_url: git@github.com:goauthentik/authentik-internal.git
          ssh_private_key: ${{ secrets.GH_MIRROR_KEY }}
          args: --tags --force --prune
        env:
          MIRROR_KEY: ${{ secrets.GH_MIRROR_KEY }}
