---
name: authentik-backend-translate-extract-compile
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

env:
  POSTGRES_DB: authentik
  POSTGRES_USER: authentik
  POSTGRES_PASSWORD: "EK-5jnKfjrGRm<77"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup authentik env
        uses: ./.github/actions/setup
      - name: run extract
        run: |
          poetry run make i18n-extract
      - name: run compile
        run: |
          poetry run ak compilemessages
          make web-check-compile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: extract-compile-backend-translation
          commit-message: "core, web: update translations"
          title: "core, web: update translations"
          body: "core, web: update translations"
          delete-branch: true
          signoff: true
